version: "3.8"


services:

    frontend:build: 
      build: ./frontend
      container_name: frontend
      restart: always

    nginx:

      build: ./nginx
      container_name: nginx
      ports:
      - "80:80"
      restart: always
      depends_on:
      - frontend